export const en = {
	'common.not_answered': 'Not answered',
	'common.choose_an_option': 'Choose an option',
	'common.choose_month': 'Choose month',
	'common.choose_one_answer': 'Choose one answer',
	'eyebrows.session_setup': 'Session setup',
	'eyebrows.eligibility': 'Core eligibility',
	'eyebrows.route_split': 'Route split',
	'eyebrows.route_asylum': 'Route-specific: asylum',
	'eyebrows.route_non_asylum': 'Route-specific: non-asylum',
	'eyebrows.identity': 'Identity readiness',
	'eyebrows.evidence_cutoff': 'Evidence: cut-off date',
	'eyebrows.evidence_recent': 'Evidence: recent months',
	'eyebrows.specialist': 'Specialist flag',
	'eyebrows.routing': 'Routing',
	'eyebrows.referral': 'Optional referral',
	'eyebrows.support': 'Support needs',
	'eyebrows.contact': 'Contact capture',
	'months.january': 'January',
	'months.february': 'February',
	'months.march': 'March',
	'months.april': 'April',
	'months.may': 'May',
	'months.june': 'June',
	'months.july': 'July',
	'months.august': 'August',
	'months.september': 'September',
	'months.october': 'October',
	'months.november': 'November',
	'months.december': 'December',
	'steps.language.title': 'Choose a language',
	'steps.language.body': 'Which language would you like to use?',
	'steps.language.hint': 'You can change language at any time without losing your answers.',
	'steps.language.check_answers_label': 'Language',
	'steps.language.error': 'Choose a language.',
	'steps.language.options.es': 'Español',
	'steps.language.options.en': 'English',
	'steps.language.options.ar': 'العربية',
	'steps.language.options.fr': 'Français',
	'steps.completion_mode.title': 'Who are you filling this in for?',
	'steps.completion_mode.body': 'Who are you filling this in for?',
	'steps.completion_mode.hint': 'Choose the option that best matches this session.',
	'steps.completion_mode.check_answers_label': 'Who you are filling this in for',
	'steps.completion_mode.error': 'Choose who you are filling this in for.',
	'steps.completion_mode.options.self': 'Myself',
	'steps.completion_mode.options.someone_else': 'Someone else, with their permission',
	'steps.completion_mode.options.support_worker': "I'm a support worker or volunteer",
	'steps.in_spain_now.title': 'Are you in Spain now?',
	'steps.in_spain_now.body': 'Are you in Spain now?',
	'steps.in_spain_now.check_answers_label': 'Are you in Spain now?',
	'steps.in_spain_now.error': 'Choose whether you are in Spain now.',
	'steps.common.options.yes': 'Yes',
	'steps.common.options.no': 'No',
	'steps.common.options.not_sure': "I'm not sure",
	'steps.residence_start.title': 'When did you start living in Spain?',
	'steps.residence_start.hint': 'An approximate month is enough.',
	'steps.residence_start.check_answers_label': 'When you started living in Spain',
	'steps.residence_start.error': 'Choose when you started living in Spain.',
	'steps.residence_start.month_error':
		'Choose the month, or say that you are not sure about the month.',
	'steps.residence_start.options.2024_or_earlier': 'In 2024 or earlier',
	'steps.residence_start.options.2025': 'In 2025',
	'steps.residence_start.options.2026': 'In 2026',
	'steps.residence_start.options.not_sure': "I'm not sure",
	'steps.residence_start.month_prompt': 'Which month was that, roughly?',
	'steps.residence_start.month_unknown': "I'm not sure about the month",
	'steps.asylum_history.title':
		'Did you apply for asylum or international protection in Spain before 1 January 2026?',
	'steps.asylum_history.body':
		'Did you apply for asylum or international protection in Spain before 1 January 2026?',
	'steps.asylum_history.hint': 'Choose one option.',
	'steps.asylum_history.check_answers_label':
		'Asylum or international protection before 1 January 2026',
	'steps.asylum_history.error':
		'Choose whether you applied for asylum or international protection in Spain before 1 January 2026.',
	'steps.five_month_stay.title': 'Have you been living in Spain during the last 5 months?',
	'steps.five_month_stay.body': 'Have you been in Spain during the last 5 months?',
	'steps.five_month_stay.hint': 'Short trips away do not always matter.',
	'steps.five_month_stay.check_answers_label': 'Have you been in Spain during the last 5 months?',
	'steps.five_month_stay.error': 'Choose whether you have been in Spain during the last 5 months.',
	'steps.five_month_stay.options.mostly_yes': 'Mostly yes, with short absences',
	'steps.asylum_documents.title': 'Do you have any documents about your asylum or protection case?',
	'steps.asylum_documents.body': 'Do you have any documents about your asylum or protection case?',
	'steps.asylum_documents.hint':
		'For example, a filing receipt, case document, letter or notification.',
	'steps.asylum_documents.check_answers_label': 'Documents about your asylum or protection case',
	'steps.asylum_documents.error':
		'Choose whether you have documents about your asylum or protection case.',
	'steps.non_asylum_route.title': 'Which of these sounds like you?',
	'steps.non_asylum_route.body': 'Which of these sounds like you?',
	'steps.non_asylum_route.hint': 'Choose all that apply.',
	'steps.non_asylum_route.check_answers_label': 'Which of these sounds like you?',
	'steps.non_asylum_route.error': 'Choose at least one option.',
	'steps.non_asylum_route.options.worked_in_spain': "I've worked in Spain",
	'steps.non_asylum_route.options.close_family_relevant':
		'I have close family here who may be relevant to this process',
	'steps.non_asylum_route.options.vulnerable_situation':
		'I may need support because of a difficult or vulnerable situation',
	'steps.non_asylum_route.options.none': 'None of these',
	'steps.identity_documents.title': 'Which identity papers do you have?',
	'steps.identity_documents.body': 'Which identity papers do you have?',
	'steps.identity_documents.hint': 'Choose all that apply.',
	'steps.identity_documents.check_answers_label': 'Identity papers',
	'steps.identity_documents.error': 'Choose at least one option.',
	'steps.identity_documents.options.current_passport': 'Current passport',
	'steps.identity_documents.options.expired_passport': 'Expired passport',
	'steps.identity_documents.options.national_identity_card': 'National identity card',
	'steps.identity_documents.options.travel_document': 'Travel document',
	'steps.identity_documents.options.no_identity_documents_now':
		'I do not have any identity documents with me now',
	'steps.evidence_before_cutoff.title':
		'Do you have any documents that could help show you were already living in Spain before January 2026?',
	'steps.evidence_before_cutoff.body':
		'Do you have any documents that could help show you were already living in Spain before January 2026?',
	'steps.evidence_before_cutoff.hint': 'Choose all that apply.',
	'steps.evidence_before_cutoff.check_answers_label':
		'Papers that may show residence before January 2026',
	'steps.evidence_before_cutoff.error': 'Choose at least one option.',
	'steps.evidence_before_cutoff.options.padron_or_registration': 'Registration or padrón',
	'steps.evidence_before_cutoff.options.housing_papers': 'Housing papers',
	'steps.evidence_before_cutoff.options.health_or_pharmacy': 'Health or pharmacy papers',
	'steps.evidence_before_cutoff.options.school_or_childcare': 'School or childcare papers',
	'steps.evidence_before_cutoff.options.work_papers': 'Work papers',
	'steps.evidence_before_cutoff.options.organisation_or_church_letter':
		'Letters from an organisation, church, or social worker',
	'steps.evidence_before_cutoff.options.travel_or_transport': 'Travel or transport papers',
	'steps.evidence_before_cutoff.options.something_else_dated_named':
		'Something else with a date and my name on it',
	'steps.evidence_before_cutoff.options.none_yet': 'I do not have any of these yet',
	'steps.evidence_recent_months.title':
		'Do you have any documents from the last 5 months that could help show you’ve been living here recently?',
	'steps.evidence_recent_months.body':
		'Do you have any documents from the last 5 months that could help show you’ve been living here recently?',
	'steps.evidence_recent_months.hint': 'Choose all that apply.',
	'steps.evidence_recent_months.check_answers_label': 'Papers from the last 5 months',
	'steps.evidence_recent_months.error': 'Choose at least one option.',
	'steps.evidence_recent_months.options.housing_papers': 'Housing papers',
	'steps.evidence_recent_months.options.health_or_pharmacy': 'Health or pharmacy papers',
	'steps.evidence_recent_months.options.school_or_childcare': 'School or childcare papers',
	'steps.evidence_recent_months.options.work_papers': 'Work papers',
	'steps.evidence_recent_months.options.organisation_or_church_letter':
		'Letters from an organisation, church, or social worker',
	'steps.evidence_recent_months.options.bank_or_money_transfer': 'Bank or money transfer records',
	'steps.evidence_recent_months.options.travel_or_dated_receipts': 'Travel or dated receipts',
	'steps.evidence_recent_months.options.something_else_dated_named':
		'Something else with a date and my name on it',
	'steps.evidence_recent_months.options.none_yet': 'I do not have any of these yet',
	'steps.specialist_flags.title':
		'Is there anything that might mean you need specialist advice before applying?',
	'steps.specialist_flags.body':
		'Is there anything that might mean you need specialist advice before applying?',
	'steps.specialist_flags.check_answers_label': 'Anything that may need specialist advice',
	'steps.specialist_flags.error': 'Choose at least one option.',
	'steps.specialist_flags.options.criminal_record_worry':
		"I'm worried about a criminal record or criminal case",
	'steps.specialist_flags.options.identity_missing_or_mismatch':
		'My identity papers are missing or do not match',
	'steps.specialist_flags.options.asylum_case_not_clear':
		"I'm not sure what happened with my asylum case",
	'steps.specialist_flags.options.want_specialist':
		"I'd rather talk this through with a specialist",
	'steps.specialist_flags.options.none': 'None of these',
	'steps.province.title': 'Which province are you in?',
	'steps.province.body': 'Which province are you in?',
	'steps.province.hint': 'This helps us show support options near you.',
	'steps.province.check_answers_label': 'Province',
	'steps.province.error': 'Choose a province.',
	'steps.province.options.madrid': 'Madrid',
	'steps.province.options.barcelona': 'Barcelona',
	'steps.province.options.valencia': 'Valencia',
	'steps.province.options.sevilla': 'Sevilla',
	'steps.province.options.malaga': 'Málaga',
	'steps.province.options.alicante': 'Alicante',
	'steps.province.options.bizkaia': 'Bizkaia',
	'steps.province.options.zaragoza': 'Zaragoza',
	'steps.province.options.murcia': 'Murcia',
	'steps.province.options.other': 'Another province',
	'steps.referral.title': 'Do you want help with the next step?',
	'steps.referral.body':
		'Based on your result, you might want help gathering papers, speaking to a specialist, or making your application.',
	'steps.referral.hint':
		'The next step could be gathering papers, speaking to a specialist, or applying.',
	'steps.referral.error': 'Choose what kind of help you want next.',
	'steps.referral.options.contact_me': "Yes, I'd like someone to contact me",
	'steps.referral.options.show_options': 'Yes, show me support options near me',
	'steps.referral.options.no_thanks': "No, I'll keep this for now",
	'steps.support_needs.title': 'What kind of help would be most useful?',
	'steps.support_needs.body': 'What kind of help would be most useful?',
	'steps.support_needs.hint': 'Choose all that apply.',
	'steps.support_needs.error': 'Choose at least one option.',
	'steps.support_needs.options.another_language': 'Help in another language',
	'steps.support_needs.options.in_person_help': 'In-person help',
	'steps.support_needs.options.help_using_phone_or_computer': 'Help using a phone or computer',
	'steps.support_needs.options.help_scanning_or_printing': 'Help scanning or printing papers',
	'steps.support_needs.options.help_gathering_papers': 'Help understanding which papers to gather',
	'steps.support_needs.options.specialist_advice': 'Specialist advice',
	'steps.contact.title': 'How should we contact you?',
	'steps.contact.body': 'How should we contact you?',
	'steps.contact.hint': 'Choose the safest way.',
	'steps.contact.error': 'Choose how we should contact you.',
	'steps.contact.detail_required_error': 'Enter the contact detail for the method you chose.',
	'steps.contact.detail_label': 'Contact detail',
	'steps.contact.options.sms': 'SMS',
	'steps.contact.options.whatsapp': 'WhatsApp',
	'steps.contact.options.phone': 'Phone call',
	'steps.contact.options.email': 'Email',
	'steps.contact.options.through_organisation': 'Through the organisation helping me now',
	'answers.residence_start.2024_or_earlier': '2024 or earlier',
	'answers.residence_start.2026': '2026',
	'answers.residence_start.not_sure': "I'm not sure",
	'answers.residence_start.2025': '2025',
	'answers.residence_start.2025_month_unknown': '2025 — month not sure',
	'answers.residence_start.2025_month': '{month} 2025',
	'answers.contact.with_value': '{method}: {value}'
} as const
